name: movieapp_bloc
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: any
  http: any
  dartz: any
  get_it: any
  pedantic: any
  # flutter_screenutil: any
  google_fonts: any
  flutter_bloc: any
  flutter_svg: any
  cached_network_image: any
  wiredash: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0


flutter:
 
  uses-material-design: true
 
  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/languages/